cmake_minimum_required(VERSION 3.20)
project({{PROJECT_NAME}} LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

find_package(Qt6 COMPONENTS {{QT_COMPONENTS}} REQUIRED)

{{SOURCES_BLOCK}}

{{TESTS_BLOCK}}
